### PR TITLE
Xmas: Let it snow

### PR DESCRIPTION
**Pull request by Mikehrn**
Screenshot 2024-12-20 at 14 27 14

### CODE REVIEW

**Review by benjaminvo — CHANGES_REQUESTED** [review]
Can't toggle away from the view mode again. Stuck here: 
CleanShot 2024-12-20 at 14 34 40@2x

**Comment by Mikehrn** [comment]
> Can't toggle away from the view mode again. Stuck here: CleanShot 2024-12-20 at 14 34 40@2x

I just fixed that, @AlexandruPopovici is going to make another change when he is back to remove the snow from the modal once you change viewmode

**Comment by benjaminvo** [comment]
> I just fixed that, @AlexandruPopovici is going to make another change when he is back to remove the snow from the modal once you change viewmode

For performance reasons? Because I actually like that the snow stays on the model when toggling off the view mode again

**Comment by Mikehrn** [comment]
> > I just fixed that, @AlexandruPopovici is going to make another change when he is back to remove the snow from the modal once you change viewmode
> 
> For performance reasons? Because I actually like that the snow stays on the model when toggling off the view mode again

It's kinda cool yeah, we can also keep it

**Review by benjaminvo — APPROVED** [review]

**Review by benjaminvo — APPROVED** [review]

**Review by didimitrie — APPROVED** [review]

**Review by andrewwallacespeckle — APPROVED** [review]

**Pull request merged**
