### PR TITLE
feat(fe2): FE2 viewer SSR optimizations

### PR DESCRIPTION
**Pull request by fabis94**
1. Removed unnecessary ClientOnly templates that prevented SSR from being able to pre-render the page and causing a bigger LCP
2. Fixed issues with GQL queries loaded during SSR that previously caused the same queries to be pulled again during CSR, causing longer loading and a bigger CSR

### CODE REVIEW

**Comment by fabis94** [comment]
@andrewwallacespeckle I removed ClientOnly components in a lot of places, I'd appreciate it if you'd actually test these changes out locally to ensure I didn't break anything

I did do testing on my own end, but maybe I've missed something

**Comment by fabis94** [comment]
Noticed a hydration mismatch in embed mode, gonna look into it

**Comment by andrewwallacespeckle** [comment]
Everything seems to work well apart from the couple of issues around Embed. 

Let me know if you can't recreate and I can jump on a call in the morning.

**Comment by fabis94** [comment]
Viewer SSR prerendering is a bigger issue: https://discord.com/channels/726756379083145269/1186669913209847839/1217759236143054869

Merging the rest in in a separate PR: https://github.com/specklesystems/speckle-server/pull/2129

**Pull request closed without merging**
