### PR TITLE
bugfix(ui-components): Scroll jumps to top on Dialog open

### PR DESCRIPTION
**Pull request by andrewwallacespeckle**

### CODE REVIEW

**Comment by benjaminvo** [comment]
@andrewwallacespeckle I tested locally. Still happens for me 🤔 I tested the invite and delete project dialogs.

I'm on mac chome 124

**Comment by andrewwallacespeckle** [comment]
> @andrewwallacespeckle I tested locally. Still happens for me 🤔 I tested the invite and delete project dialogs.
> 
> I'm on mac chome 124

I'm on the same version on mac, and it's working. 

Can you make sure you run `yarn build:public`? 

If that doesn't work, can you open a dialog and check in inspector. It should add a `dialog-open` class to the HTML tag. Is this happening?

**Comment by benjaminvo** [comment]
@andrewwallacespeckle Ah, that was it. Works great now, will review.

**Review by benjaminvo — APPROVED** [review]
Works great! A bit annoying that we need to overwrite headlessui with these CSS classes but that's how it is.

**Pull request merged**
