### PR TITLE
fix: preview 360 images occasionally not displayed

### PR DESCRIPTION
**Pull request by Easoncan**
## Screenshots:

image

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [x] I have added appropriate tests.
- [x] I have updated or added relevant documentation.

### CODE REVIEW

**Comment by benjaminvo** [comment]
Hi @Easoncan. Thanks for contributing! Can you provide some more information about what the bug is, how to reproduce it, and how it has been improved after your fix? If possible you can also link to a public model that has this bug.

**Comment by Easoncan** [comment]
> Hi @Easoncan. Thanks for contributing! Can you provide some more information about what the bug is, how to reproduce it, and how it has been improved after your fix? If possible you can also link to a public model that has this bug.

In some cases, the value of parentWidth and parentHeight is 0, so modified to a better way to get the correct parentHeight in all cases
屏幕录制2024-03-20 10 19 19

**Comment by Easoncan** [comment]
There is another situation. When the 360 ​​image is loaded, the calculation is not retriggered. As a result, the 360 ​​image is not in the corresponding position and displays blank.

**Comment by fabis94** [comment]
added dim, he's our expert on 360 previews

**Comment by didimitrie** [comment]
hey @Easoncan! This LGTM - if you resolve the conflict (it baffles me a bit), we'll merge - and thanks for making this more reliable 🙇

**Comment by fabis94** [comment]
@Easoncan We've picked your changes up and polished them up (e.g. merged w/ current main) and are going to merge them as part of this PR: https://github.com/specklesystems/speckle-server/pull/2494

Thanks for your contribution!

**Pull request closed without merging**
