### PR TITLE
fix(server auth): fix oidc stategy

### LINKED ISSUE #1374: OIDC Error on trying to authenticate
## Prerequisites

I've set up docker deployment with Speckle. 

I've managed to make the local strategy work fine.
I've managed to get Github strategy working. 

I'm using an Authentik self-hosted provider. Setup for OIDC, implicit flow.

the .env strategy as below.

STRATEGY_OIDC=true
OIDC_NAME="NAME"
OIDC_DISCOVERY_URL="https://DOMAIN/application/o/APP/.well-known/openid-configuration"
OIDC_CLIENT_ID="SOME_ID"
OIDC_CLIENT_SECRET="SUPER_SECRET"

The Authentik works fine with multiple apps already.

## Describe the bug
When going through auth flow i'm getting the following response.

`[{"err":"insert into \"authorization_codes\" (\"appId\", \"challenge\", \"id\", \"userId\") values ($1, DEFAULT, $2, $3) - null value in column \"challenge\" of relation \"authorization_codes\" violates not-null constraint"}](url)`

On server logs i can see:

{
  "level": "error",
  "time": "2023-02-15T16:41:41.984Z",
  "component": "modules",
  "err": {
    "type": "DatabaseError",
    "message": "insert into \"authorization_codes\" (\"appId\", \"challenge\", \"id\", \"userId\") values ($1, DEFAULT, $2, $3) - null value in column \"challenge\" of relation \"authorization_codes\" violates not-null constraint",
    "stack": "error: insert into \"authorization_codes\" (\"appId\", \"challenge\", \"id\", \"userId\") values ($1, DEFAULT, $2, $3) - null value in column \"challenge\" of relation \"authorization_codes\" violates not-null constraint\n    at Parser.parseErrorMessage (/speckle-server/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/speckle-server/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/speckle-server/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/speckle-server/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:324:12)\n    at readableAddChunk (node:internal/streams/readable:297:9)\n    at Readable.push (node:internal/streams/readable:234:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)",
    "length": 335,
    "name": "error",
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (339f2de06267921bccd047e8cbd3a8ee4d974fccf5, spklwebapp, 09782ac043, null, 2023-02-15 16:41:41.981864+00, 600000).",
    "schema": "public",
    "table": "authorization_codes",
    "column": "challenge",
    "file": "execMain.c",
    "line": "1959",
    "routine": "ExecConstraints"
  },
  "msg": "insertinto \"authorization_codes\" (\"appId\", \"challenge\", \"id\", \"userId\") values ($1, DEFAULT, $2, $3) - null value in column \"challenge\" of relation \"authorization_codes\" violates not-null constraint"
}

for the postgres logs:

`2023-02-15 16:41:41.982 UTC [30] ERROR:  null value in column "challenge" of relation "authorization_codes" violates not-null constraint
2023-02-15 16:41:41.982 UTC [30] DETAIL:  Failing row contains (339f2de06267921bccd047e8cbd3a8ee4d974fccf5, spklwebapp, 09782ac043, null, 2023-02-15 16:41:41.981864+00, 600000).`

I can confirm that the postgres table authorization_codes has a column challenge with "Not NULL?" enabled.

In my Authentik provider the action shows as authorized:

{
    "geo": {
//some location
    },
    "flow": "ID",
    "scopes": "openid profile email",
    "http_request": {
        "args": {
            "query": "client_id=CLIENTID&scope=openid+profile+email&response_type=code&redirect_uri=https://DOMAIN/auth/oidc/callback&state=UNIQUE_STRING&code_challenge=UNIQUE_STRING&code_challenge_method=S256"
        },
        "path": "/api/v3/flows/executor/default-provider-authorization-implicit-consent/",
        "method": "GET"
    },
    "authorized_application": {
        "pk": "ID",
        "app": "authentik_core",
        "name": "NAME",
        "model_name": "application"
    }
}

The user gets created inside the postgres db. 

Just to mess with it even more i removed the Postgress Null constraint which just leads to redirect to login screen after going through the following url

image

Not sure if this is a problem with Authentik, or i might have misconfigured something. 

## System Info

Tried Speckle  speckle/speckle-server:2 &  speckle/speckle-server:latest
Tried "postgres:13.1-alpine" & "postgres:13.10-alpine"
to no avail.

- [x] I read the [contribution guidelines](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)
- [x] I checked the [documentation](https://speckle.guide/) and found no answer.
- [x] I checked [existing issues](../issues?q=is%3Aissue) and found no similar issue. 
- [x] I checked the [community forum](https://speckle.community/) for related discussions and found no answer.
- [x] I'm reporting the issue to the correct repository (see also [speckle-server](https://github.com/specklesystems/speckle-server), [speckle-sharp](https://github.com/specklesystems/speckle-sharp), [specklepy](https://github.com/specklesystems/specklepy), [speckle-docs](https://github.com/specklesystems/speckle-docs), and [others](https://github.com/orgs/specklesystems/repositories))

### PR DESCRIPTION
**Pull request by gjedlicska**
make sure the passport authentication works on the same request scope for auth and callback

fix #1374

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

### CODE REVIEW

**Comment by gjedlicska** [comment]
Hey @spgoad

We've ran into an issue with your IODC implementation. This PR fixes stuff on our end, could you verify that this is still working for you?
Thanks :)

**Comment by spgoad** [comment]
@gjedlicska Yes it works just fine!

I see that common passportAuthenticate now - sorry I missed that the first time around.

> Hey @spgoad
> 
> We've ran into an issue with your IODC implementation. This PR fixes stuff on our end, could you verify that this is still working for you? Thanks :)

**Comment by gjedlicska** [comment]
Hey @spgoad thanks for the quick confirmation.

Just out of curiosity, which OIDC provider have you used successfully with the previous version?

**Comment by spgoad** [comment]
> Just out of curiosity, which OIDC provider have you used successfully with the previous version?

Good question. It's an internal identity provider that implements the OIDC standard - so it's not one of the major known providers.

**Pull request merged**
