### PR TITLE
WIP: Viewer in docker

### LINKED ISSUE #83: Viewer missing in Dockerfile
### Expected vs. Actual Behavior

Docker build fails because of missing viewer packages. 
 The current command used to install packages to build the frontend, `npm ci` will stop if the package-lock.json is not up to date. 

### Reproduction Steps & System Config (win, osx, web, etc.)

Just run `docker build .` 

### Proposed Solution (if any)

Until viewer is published as an npm package, it has to be build as part of the build process.

Docker build should be part of the CI process to check for basic errors.

### PR DESCRIPTION
**Pull request by gjedlicska**
This is an attempt to fix #83 

The build now succeeds, but it takes quite a while to finish. Also the result for the frontend quite large ~1.6MB

The I haven't tested the result yet, hence the WIP status. 
@didimitrie could you point me to some sample data to test the viewer running in the docker container?

### CODE REVIEW

**Comment by peterjgrainger** [comment]
can we store the viewer in npm? making the Dockerfile a little more complex

**Comment by peterjgrainger** [comment]
Actually it is already in npm https://www.npmjs.com/package/@speckle/speckle-viewer

I think the package.json references the wrong module. should be `@speckle/speckle-viewer` instead of `@speckle/viewer`?

**Comment by gjedlicska** [comment]
This is definitely not the current viewer package. It was last updated 3years ago.

**Comment by gjedlicska** [comment]
Cool, this unblocks #73 again.

**Pull request merged**
