### PR TITLE
Alex/sao

### LINKED ISSUE #1014: Implement SAO

### PR DESCRIPTION
**Pull request by AlexandruPopovici**
# Realtime Screen Space Ambient Occlusion

## Description & motivation
We've added screen space ambient occlusion to our viewer. We're using three's SAO implementation with several changes and improved normal reconstruction to avoid artifacts caused by broken vertex normals.
Closes #1014 

## Changes:
- Added the rendering pipeline which renders into SAO-related framebuffers before applying the SAO result on top of the backbuffer
- Complete description [here](https://www.notion.so/speckle/SAO-Ambient-Occlusion-ee139d3786444d5986990ed15b87023c)

## Checklist:

- [x] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [x] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [x] My commits are related to the pull request and do not amend unrelated code or documentation.
- [x] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [x] I have updated or added relevant documentation.

## References
- https://research.nvidia.com/sites/default/files/pubs/2012-06_Scalable-Ambient-Obscurance/McGuire12SAO.pdf
- https://wickedengine.net/2019/09/22/improved-normal-reconstruction-from-depth/

### CODE REVIEW

**Comment by didimitrie** [comment]
Hi @AlexandruPopovici, everything looks amazing, though i did manage to create some artifacts: 

https://user-images.githubusercontent.com/7696515/193121802-f79518df-6f37-49ab-a55e-b962da59ba34.mov

What I did: 
- double click on a small object (to zoom extents to it)
- zoom out by scrolling

This artefacts resolve themselves on a global scene "zoom extents". You did mention we'll need to be careful with camera near/far etc. - and i guess this has to do with that 😅

**Comment by AlexandruPopovici** [comment]
Thanks for pointing this out, I totally missed it :)

**Comment by AlexandruPopovici** [comment]
@didimitrie 
Can you please check now? The artifacts I was getting in the described scenario were different so I can't really tell. I get no artifacts anymore when zooming in on small objects

**Review by didimitrie — APPROVED** [review]
amazing!

**Pull request merged**
